gemini-hlsw/lucupy

lucupy/minimodel/group.py
lucupy/minimodel/observation.py
lucupy/minimodel/program.py
lucupy/observatory/gemini/geminiobservation.py
pyproject.toml

This is a substantial refactor of time calculations:
1. Logic for time calculation has now been moved from `AndGroup` to `Group`.
2. `Program` now differentiates between awarded time used and time used across `Observation`s / `Group`s.
3. Bugfix: missing `return` for `sum`.
4. Bugfix: rewrote `sum` statements to use a generator and a default of `timedelta()` for the zero element. (Before `int` was assumed, causing an error.)
5. Warnings cleared.

SCHED-250: Change how time calculations are handled

---

lucupy/minimodel/group.py
lucupy/minimodel/observation.py
lucupy/minimodel/semester.py
lucupy/minimodel/timingwindow.py
poetry.lock
pyproject.toml
tests/test_minimodel.py
tests/test_output.py

It is now possible, by giving a `date` to a static lookup function in `Semester`, to get the `Semester` in which the `date` belongs. Additionally, the start date and the end date of a `Semester` can be obtained.
These changes are essential for the `ResourceMock` modification where parsed data is extended to the end of a `Semester`.

SCHED-255: Refinement to Semester information

---

lucupy/minimodel/__init__.py
lucupy/minimodel/group.py
lucupy/minimodel/ids.py
lucupy/minimodel/observation.py
lucupy/minimodel/program.py
poetry.lock
pyproject.toml
tests/fixtures.py
tests/test_group.py
tests/test_output.py

Scheduling groups from OCS have names that are just integers, and thus do not make a lot of sense. They can also clash between programs, so, e.g., two programs could have a scheduling group with the name of `10`.
Now a `program_id` field has been added to `Group`, and a `unique_id` method that:
1.  In the case of an observation group, just returns the name of the observation in the group.
2. In the case of a scheduling group (including the root group) has the name of the form `program_id:group_id` to make it unique and human-readable.
Test fixtures and cases have been added as well.
Additionally, all ID aliases were moved to their own file, because this introduced circular dependencies.

SCHED-276: Add ProgramID and a unique_id method to Group

---

lucupy/decorators/__init__.py
lucupy/minimodel/atom.py
lucupy/minimodel/constraints.py
lucupy/minimodel/group.py
lucupy/minimodel/magnitude.py
lucupy/minimodel/observation.py
lucupy/minimodel/program.py
lucupy/minimodel/qastate.py
lucupy/minimodel/resource.py
lucupy/minimodel/semester.py
lucupy/minimodel/target.py
lucupy/minimodel/timingwindow.py
lucupy/sky/constants.py
lucupy/sky/moon.py
lucupy/sky/utils.py
poetry.lock
pyproject.toml
tests/fixtures.py
tests/test_immutable.py

In this PR:
* I added an `immutable` decorator, which redirects `copy` and `deepcopy` to return `self` instead of an actual copy of self.
* I cleaned up some dataclasses, to avoid using mutable members in hashing and removing all unsafe hashing, and marking members with `field` options to improve the code.
* Added gelidum library to freeze data structures that should be truly immutable (i.e. freezing lists and dicts instead of just their assigned references).
* Removed warnings with `# noqa` tag.
* Added a test case to test the `immutable` decorator and the results of `deepcopy`ing a `Program`.

SCHED-270: immutable decorator and suppression of deepcopy of immutable objects

---

lucupy/minimodel/atom.py
lucupy/minimodel/observation.py
pyproject.toml

Add partner_used and program_used attributes to the atom class and update observation methods to use these. These are needed for the greedymax internal time accounting.
Also, rebased with the latest program/group/observation id changes.

Update partner/program times in atoms

---

lucupy/helpers/__init__.py
tests/test_helpers.py

Linear Interpolation between two values in an Enum with a certain number of steps.
This was recommended by Fredrik as the way we should be filling in missing weather data instead of using the `ffill()` pandas functionality that we are using now.

SCHED-393: Enum linear interpolation.

---

lucupy/helpers/__init__.py
pyproject.toml
tests/test_helpers.py

Before, when we linearly interpreted between the values of an `Enum`, we chose the floor value, which is not what we wanted We want to clamp values to the value above the linearly interpolated value, as in the case in something like `CloudCover`, a 0.54 should, for example, be interpreted as a `0.7` and not a `0.5`.

SCHED-393: Fixing enum lerp.

---

lucupy/helpers/__init__.py
pyproject.toml
tests/test_helpers.py

`lerp_radians` takes the smallest angle between `start_value` and `end_value` and linearly interpolates between them.
The interpolation between antipodal points is, understandably, unpredictable. For example:
1. Interpolation between `π/2` and `-π/2` (or equivalently `3π/2`) is done clockwise; whereas
2. Interpolation between `-π/2` (or equivalently `3π/2`) and `π/2` is done counterclockwise.
Thus, `lerp_radians(np.pi/2, -np.pi/2) == lerp_radians(-np.pi/2, np.pi/2)[::-1]`.
A small epsilon added to a parameter can flip the interpolation if necessary.
The test cases have been improved to use `np.allclose` to handle floating point errors.

SCHED-398: Added lerp_radians for wind_dir and improved test cases.

---

lucupy/helpers/__init__.py
pyproject.toml
tests/test_helpers.py

Adding `lerp_degrees` to try to fix a strange thing happening in OCS weather direction linear interpolation.

SCHED-398C: lerp_degrees

---

lucupy/minimodel/constraints.py
pyproject.toml

SCHED-365: Removing start_time from Variant.

---

lucupy/minimodel/observation.py

Acq time added based on obs_class. Makes the planned and charged times by the optimizer match.

Add acquisition overhead to planned program and partner time calculation

---

lucupy/minimodel/observation.py
lucupy/minimodel/resource.py
lucupy/minimodel/site.py
pyproject.toml

`Site` has been cleaned up considerably.
* There is no need to change the format of the site name for `EarthLocation` lookups. (tested)
* `resource` was added to `Site`.
* Now `location`, `timezone`, and `resource` can be passed into `Site.
* `Observation` now returns its `Site` as one of its required resources. This means no changes need to be made to the Scheduler parsing logic.

GSCHED-542: Added Site.resource and site resource to Observation.

---

lucupy/types/__init__.py
pyproject.toml

Moving the `Instantiable` type to lucupy since it has multiple generic uses and will be used in the omegaconf parameters for the Selector's BUFFER as per GSCHED-605.

SCHED-605: Moving Instantiable to lucupy.

---

lucupy/minimodel/resource.py
pyproject.toml

Adding the new type attribute to the NIR_INSTRUMENTS definition is required so that the checks as to whether one of these instruments is in required_resources will work.
This fixes the bug that telluric observations were no longer being scheduled.

GSCHED-640: fix NIR_INSTRUMENTS

---

lucupy/types/__init__.py
pyproject.toml

Add definition of a day as a `timedelta`.

SCHED-647: Add Day definition.

---

lucupy/instruments/__init__.py
lucupy/instruments/instruments.py
lucupy/minimodel/observation.py
lucupy/minimodel/resource.py
lucupy/minimodel/site.py
lucupy/observatory/abstract/__init__.py
lucupy/observatory/gemini/geminiproperties.py
lucupy/resourcemanager/resource_manager.py
pyproject.toml

This PR does the following:
* Collectts and distinguishes the instruments, that were spread across multiple files.
* Adds the `hash` dunder method to `Resource`, which should make set `contains` checks not dismiss properly.
* `Site.resource` now created through the `ResourceManager`.
* Big cleanup of `GeminiProperties`, which should be `Resource`s that are instruments that are Gemini-specific.

SCHED-662: Removal of manually created Resources and code simplification

---

lucupy/minimodel/group.py
lucupy/minimodel/program.py
pyproject.toml

Calculate effective user priority for groups and the program based on the observation settings.
Based only on active science and program calibration observations.
The program mean priority is used in the scoring algorithm.
Returned group constraints are a list now rather than a frozenset.

GSCHED: add methods to handle user priority

---

lucupy/minimodel/__init__.py
lucupy/minimodel/group.py
lucupy/minimodel/obs_filter.py
lucupy/minimodel/observation.py
lucupy/minimodel/program.py
pyproject.toml

This PR does the following:
* Adds common filters for `Observation` (done to avoid recreating a `FrozenSet[ObservationClass]` with every loop index).
* Generalizes the logic for fetching `List[Observation]`.
* Adds values to `Priority` so that we can get a mean priority score for a `Program`.

SCHED-650: Cleanup for priorities and observation filtering.

---

lucupy/minimodel/constraints.py
pyproject.toml

This should be more in agreement with what QCs use. Observations that must be done at higher airmass need the constraint set in the observation in the OT.

Change default max airmass to 2.05

---

lucupy/sky/brightness.py
lucupy/sky/moon.py
pyproject.toml
tests/test_moon.py

This PR does two things:
1. It returns a `Distance` (in m) instead of a `float` in calculating the moon distance in high precision calculations.
2. It returns the `Distance` (in m) instead of `float` (originally calculated in equatorial radii) calculated in the moon distance in low precision calculations.

SCHED-679: Fixing Moon low precision calculations

---

lucupy/observatory/gemini/geminiproperties.py
pyproject.toml

The previous definition of the lists of Gemini instruments put them in a class and so the sets of instrument types became sets of the Instruments class instead of sets of Resources. Therefore, GreedyMax could not identify whether an observation used a NIR instrument and did not process the tellurics correctly, not scheduling them. This change makes _STANDARD_INSTRUMENTS and _NIR_INSTRUMENTS sets of Resources so that they can be compares to the observation Resources.

Update instrument set definitions to fix scheduling of tellurics
