- lucupy/minimodel/group.py
- lucupy/minimodel/observation.py
- lucupy/minimodel/program.py
- lucupy/observatory/gemini/geminiobservation.py
- lucupy/types/__init__.py
- pyproject.toml
Testing with `timeit`, creating and reusing one`timedelta()` instead of many has performance benefits.
> SCHED-251: Fixed IGRINS check and increased performance.

- lucupy/minimodel/group.py
- lucupy/minimodel/ids.py
- lucupy/minimodel/observation.py
- lucupy/minimodel/program.py
- pyproject.toml
- tests/test_group.py
> SCHED-363: Convert to / from observation group ID and observation ID and test cases.

- lucupy/minimodel/group.py
- lucupy/minimodel/ids.py
- lucupy/minimodel/observation.py
- pyproject.toml
Changes to support GreedyMax observation splitting and calibration selection
> SCHED-354/355

- lucupy/minimodel/group.py
- lucupy/minimodel/observation.py
- pyproject.toml
> GSCHED-412B

- lucupy/minimodel/observation.py
- lucupy/minimodel/observationmode.py
- lucupy/observatory/abstract/__init__.py
- pyproject.toml
Also removed multiple checks for None objects.
> SCHED-424: Trying to fix circular import

- lucupy/minimodel/atom.py
- lucupy/minimodel/group.py
- lucupy/minimodel/observation.py
- pyproject.toml
Needed for associated scheduler PR
> Add obs_mode to atom class, obs_mode methods to observation/group

- lucupy/sky/altitude.py
- lucupy/sky/brightness.py
- pyproject.toml
> SCHED-466: Reverting augmented operators that crash numpy.

- lucupy/timeutils/__init__.py
- pyproject.toml
Cleanup of the timeutils functions. This will break some things in scheduler due to name changes in an attempt to standardize and clarify, but I will fix them after this is merged.
> SCHED-359: timeutils cleanup.

- lucupy/minimodel/atom.py
- lucupy/minimodel/group.py
- lucupy/minimodel/observation.py
- lucupy/minimodel/program.py
- pyproject.toml
As in the title, needed for the related scheduler changes.
> Add not_charged time to atom/observation/group/program

- lucupy/minimodel/resource.py
- pyproject.toml
Add type attribute to Resource class and associated ResourceType class.
Add Phoenix to the list of NIR instruments.
> GSCHED-607: Add Resource type and Pheonix

- lucupy/minimodel/resource.py
- pyproject.toml
Fixing the type of `resource_type` from `int` to `ResourceType`.
> SCHED-636: Fixing type for ResourceType.

- lucupy/minimodel/constraints.py
- pyproject.toml
`VariantChange` no longer had `Optional` for wind direciton and wind speed.
Some safety checking added via a `__post_init__` method.
> SCHED-649: Modify VariantChange.

- lucupy/minimodel/constraints.py
- pyproject.toml
Rename `VariantChange` to `VariantSnapshot` for clarity, and move logic to create a `Variant` to it.
> SCHED-653: Change VariantChange to VariantSnapshot.

- lucupy/observatory/gemini/geminiobservation.py
- pyproject.toml
> Attempt to fix.

- lucupy/minimodel/observation.py
- lucupy/observatory/gemini/geminiproperties.py
- pyproject.toml
Some import issues causing circular dependencies and preventing the GraphQL:
```
test_graphql_queries.test_schedule_query
```
from working individually.
> SCHED-676: Fixing import issues.

- lucupy/minimodel/observation.py
- pyproject.toml
Added a preimaging attribute flag to the observation class.
> GSCHED-656: support MOS pre-imaging

- lucupy/types/__init__.py
- pyproject.toml
As the title, for setting altitude min/max's
> Added MinMax class to types

- lucupy/minimodel/target.py
- pyproject.toml
These will be supplied either by GPP, or calculated by the Scheduler proper.
> SCHED-683: Removing RA and dec from NonsiderealTarget.

- lucupy/minimodel/group.py
- lucupy/minimodel/observation.py
- lucupy/minimodel/program.py
- lucupy/minimodel/timeallocation.py
- pyproject.toml
- tests/fixtures.py
- tests/test_immutable.py
- tests/test_output.py
This generalizes the Group, TimeAllocation, and Program classes to support OCS and GPP.
> GSCHED-702: Minimodel updates to support GPP

- lucupy/helpers/__init__.py
- lucupy/minimodel/group.py
- lucupy/minimodel/ids.py
- pyproject.toml
As the title, needed to support sim mode Collector changes.
> GSCHED-708: Add unique_list helper, group class cleanup

- lucupy/minimodel/ids.py
- pyproject.toml
As the title, to fix issues in greedymax.
> Reintroduce ObservationID.program_id()

- lucupy/observatory/gemini/geminiproperties.py
- pyproject.toml
Added `GMOS_S` and `GMOS_N` to `_STANDARD_INSTRUMENTS` list.
Changed the way each resource is checked if it is an instrument or not.
> Fixed resource/instrument comparison

- lucupy/minimodel/observation.py
- lucupy/minimodel/resource_type.py
- pyproject.toml
Added disperser, fpu and filters.
Updated lucupy version.
Changed the way to check if a resource is an instrument.
> Added filter to resource types and functions

- lucupy/helpers/__init__.py
- pyproject.toml
Added this function for searching for a string in a list to helpers as it is used by <ocs/gpp>programprovider.
> GSCHED-767: Add search_list to helpers

- lucupy/minimodel/group.py
- pyproject.toml
Small changes to group.py for initial OR groups support, to be consistent with gpprprogramprovider.
> GSCHED-848: changes for initial OR group support
